@retry(2)
Feature: AdminPortalFR
To verify the 'customer support' link in the 'MindManager Account help' screen in French

Background: Pre-condition
	Given User is on Customer Admin Portal website
	When User accepts Optanon cookies

@MindManager @Accounts @HelpButton @AdminPortal @App_QA @App_Staging @Qase[WEB-2998] @Locale_French @JIRA[MMCV-10105,MMCV-10262,MMCV-10377] @Cleanup @Build_24.0.110 @Upd_Qase
Scenario: Customer_Support_Link_from_Admin_Portal_Welcome_Screen_FR
	When User clicks 'Aide' button
	Then User sees 'contacter l’assistance' hyperlink on Right Side panel
	Then Following text is displayed under each header:
		| Header                                          | ExpectedText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
		| Aide relative aux comptes MindManager           | Votre compte MindManager donne accès au plein potentiel de MindManager. Cela ne prend qu’une minute pour créer un compte, et c’est gratuit !                                                                                                                                                                                                                                                                                                                                                    |
		| À quoi sert un compte MindManager ?             | Le compte MindManager est votre identification unique pour MindManager.                                                                                                                                                                                                                                                                                                                                                                                                                         |
		| À quoi un compte MindManager donne-t-il accès ? | Votre compte MindManager donne accès à la licence perpétuelle, à l'abonnement et/ou aux services d'assistance. C'est également votre identité unique lors de l'utilisation de fonctions spéciales comme MindManager Snap, Publishing, Coédition et l'application MindManager pour Microsoft Teams.                                                                                                                                                                                              |
		| Puis-je utiliser mes identifiants Mindjet ?     | Dans la plupart des cas, non. Si vous disposez d’un compte Mindjet Connect ou Mindjet Files, d’un Mindjet ID ou de maps pour ce compte, vos anciens identifiants de connexion ne fonctionneront pas et vous devrez créer un nouveau compte MindManager.Si vous avez déjà créé un compte MindManager pour utiliser MindManager Snap, la publication ou la coédition, vous pouvez effectivement utiliser ce compte pour vous connecter.                                                           |
		| Je n’ai pas reçu mon e-mail de vérification !   | Dans certains cas, les filtres antispam peuvent bloquer nos e-mails. Essayez d'ajouter l’adresse noreply@mindmanager.com à votre liste d’expéditeurs approuvés. Vous pouvez également essayer d'appuyer sur le bouton « Renvoyer l'e-mail ». Dans ce cas, patientez quelques minutes, car la réception d'e-mails peut parfois prendre un certain temps. Si vous n'avez toujours pas reçu l'e-mail de vérification après avoir essayé les méthodes précédentes, veuillez contacter l’assistance. |
	When User click 'contacter l’assistance' hyperlink on Right Side panel
	When User switches to '1' tab
	Then page url is 'https://www.mindmanager.com/fr/support/'
	Then User sees 'Bienvenue sur le site d’assistance de MindManager' page header

@MindManager @Accounts @HelpButton @AdminPortal @App_QA @App_Staging @Qase[WEB-2997] @Locale_French @JIRA[MMCV-10105,MMCV-10262,MMCV-10377] @Cleanup @Build_24.0.110 @Upd_Qase
Scenario: Customer_Support_Link_from_Sign_In_Screen_FR
	When User clicks 'Se connecter' button
	When User clicks 'Aide' button
	Then User sees 'contacter l’assistance' hyperlink on Right Side panel
	Then Following text is displayed under each header:
		| Header                                          | ExpectedText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
		| Aide relative aux comptes MindManager           | Votre compte MindManager donne accès au plein potentiel de MindManager. Cela ne prend qu’une minute pour créer un compte, et c’est gratuit !                                                                                                                                                                                                                                                                                                                                                    |
		| À quoi sert un compte MindManager ?             | Le compte MindManager est votre identification unique pour MindManager.                                                                                                                                                                                                                                                                                                                                                                                                                         |
		| À quoi un compte MindManager donne-t-il accès ? | Votre compte MindManager donne accès à la licence perpétuelle, à l'abonnement et/ou aux services d'assistance. C'est également votre identité unique lors de l'utilisation de fonctions spéciales comme MindManager Snap, Publishing, Coédition et l'application MindManager pour Microsoft Teams.                                                                                                                                                                                              |
		| Puis-je utiliser mes identifiants Mindjet ?     | Dans la plupart des cas, non. Si vous disposez d’un compte Mindjet Connect ou Mindjet Files, d’un Mindjet ID ou de maps pour ce compte, vos anciens identifiants de connexion ne fonctionneront pas et vous devrez créer un nouveau compte MindManager.Si vous avez déjà créé un compte MindManager pour utiliser MindManager Snap, la publication ou la coédition, vous pouvez effectivement utiliser ce compte pour vous connecter.                                                           |
		| Je n’ai pas reçu mon e-mail de vérification !   | Dans certains cas, les filtres antispam peuvent bloquer nos e-mails. Essayez d'ajouter l’adresse noreply@mindmanager.com à votre liste d’expéditeurs approuvés. Vous pouvez également essayer d'appuyer sur le bouton « Renvoyer l'e-mail ». Dans ce cas, patientez quelques minutes, car la réception d'e-mails peut parfois prendre un certain temps. Si vous n'avez toujours pas reçu l'e-mail de vérification après avoir essayé les méthodes précédentes, veuillez contacter l’assistance. |
	When User click 'contacter l’assistance' hyperlink on Right Side panel
	When User switches to '1' tab
	Then page url is 'https://www.mindmanager.com/fr/support/'
	Then User sees 'Bienvenue sur le site d’assistance de MindManager' page header

@MindManager @Accounts @HelpButton @AdminPortal @App_QA @App_Staging @Qase[WEB-2996] @Locale_French @JIRA[MMCV-10105,MMCV-10262,MMCV-10377] @Cleanup @Build_24.0.110 @Upd_Qase
Scenario: Customer_Support_Link_from_Admin_Create_Account_Screen_FR
	When User clicks 'Créer un compte' button
	When User clicks 'Aide' button
	Then User sees 'contacter l’assistance' hyperlink on Right Side panel
	Then Following text is displayed under each header:
		| Header                                          | ExpectedText                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
		| Aide relative aux comptes MindManager           | Votre compte MindManager donne accès au plein potentiel de MindManager. Cela ne prend qu’une minute pour créer un compte, et c’est gratuit !                                                                                                                                                                                                                                                                                                                                                    |
		| À quoi sert un compte MindManager ?             | Le compte MindManager est votre identification unique pour MindManager.                                                                                                                                                                                                                                                                                                                                                                                                                         |
		| À quoi un compte MindManager donne-t-il accès ? | Votre compte MindManager donne accès à la licence perpétuelle, à l'abonnement et/ou aux services d'assistance. C'est également votre identité unique lors de l'utilisation de fonctions spéciales comme MindManager Snap, Publishing, Coédition et l'application MindManager pour Microsoft Teams.                                                                                                                                                                                              |
		| Puis-je utiliser mes identifiants Mindjet ?     | Dans la plupart des cas, non. Si vous disposez d’un compte Mindjet Connect ou Mindjet Files, d’un Mindjet ID ou de maps pour ce compte, vos anciens identifiants de connexion ne fonctionneront pas et vous devrez créer un nouveau compte MindManager.Si vous avez déjà créé un compte MindManager pour utiliser MindManager Snap, la publication ou la coédition, vous pouvez effectivement utiliser ce compte pour vous connecter.                                                           |
		| Je n’ai pas reçu mon e-mail de vérification !   | Dans certains cas, les filtres antispam peuvent bloquer nos e-mails. Essayez d'ajouter l’adresse noreply@mindmanager.com à votre liste d’expéditeurs approuvés. Vous pouvez également essayer d'appuyer sur le bouton « Renvoyer l'e-mail ». Dans ce cas, patientez quelques minutes, car la réception d'e-mails peut parfois prendre un certain temps. Si vous n'avez toujours pas reçu l'e-mail de vérification après avoir essayé les méthodes précédentes, veuillez contacter l’assistance. |
	When User click 'contacter l’assistance' hyperlink on Right Side panel
	When User switches to '1' tab
	Then page url is 'https://www.mindmanager.com/fr/support/'
	Then User sees 'Bienvenue sur le site d’assistance de MindManager' page header